name: Release Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Release PR
        uses: MateSousa/create-release-bot@master
        with:
          repo_owner: MateSousa
          repo_name: create-release
          base_branch: master
          target_branch: release
          github_token: ${{ secrets.TOKEN }}
          github_event: ${{ toJson(github.event) }}
