name: Release Workflow

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Release PR
        uses: MateSousa/create-release-bot@master
        with:
          repo_owner: MateSousa
          repo_name: create-release-bot
          base_branch: master
          target_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_event: ${{ toJson(github.event) }}
